### ISSUE TITLE
Page movement cause unexpected error

### ISSUE THREAD

**Issue by sasigume** [pawaaapp/napoancom#131]

**Comment by sasigume** [comment]
Maybe related to this error?

```
[GET] /_next/data/Ew2sb2w5w2MNHWdgBcwgq/index.json
17:06:41:52
2021-04-04T08:06:42.820Z	071b96a9-bfff-4916-b4a3-1a02bc6db8c2	WARN	TOTAL CONTENTFUL LIMIT is 700
2021-04-04T08:06:43.675Z	071b96a9-bfff-4916-b4a3-1a02bc6db8c2	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, open './public/ads.txt'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, open './public/ads.txt'","code":"ENOENT","errno":-2,"syscall":"open","path":"./public/ads.txt","stack":["Error: ENOENT: no such file or directory, open './public/ads.txt'","    at Object.openSync (fs.js:462:3)","    at Object.writeFileSync (fs.js:1384:35)","    at publishAdsTxt (/var/task/.next/server/pages/index.js:4942:27)","    at getStaticProps (/var/task/.next/server/pages/index.js:5046:3)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:28:1737)","    at async /var/task/node_modules/next/dist/next-server/server/next-server.js:112:97","    at async /var/task/node_modules/next/dist/next-server/server/next-server.js:105:142","    at async Server.renderToHTMLWithComponents (/var/task/node_modules/next/dist/next-server/server/next-server.js:137:387)","    at async Server.renderToHTML (/var/task/node_modules/next/dist/next-server/server/next-server.js:138:522)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: ENOENT: no such file or directory, open './public/ads.txt'","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:326:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```

**Comment by sasigume** [comment]
This?

https://github.com/vercel/next.js/pull/17203

**Comment by sasigume** [comment]
Seems like ads.txt has nothing to do with this issue.

**Comment by sasigume** [comment]
Trying disabling color theme cookie

**Comment by sasigume** [comment]
Doesn't work. Content is loaded but only showswhite screen (localhost)
